config/routes.rb
Totalizator::Application.routes.draw do
  
  resources :user_bits


  #resources :line_items


  resources :bits


  resources :wallets


  #get "events/index"

  resources :events
  #get ':controller/:action/:event_id'

  #resources :posts
  resources :events do
    post :make_bit, :on => :member
  end
  
  resources :events do
      post :it_exist, :on => :member
  end

  resources :bits do
    collection do 
      post :pay_bits
    end
  end
  


resources :bits do
    collection do 
      post :pay_this_bit
    end
end



  resources :bits do
    collection do 
      post :see_balance
    end
  end

  resources :events do
    collection do 
      post :make_status_bits
    end
  end
  
  resources :events do
    collection do 
      post :cancel_status_bits
    end
  end
  devise_for :users

  root to: "home#index"


end

app/models/event.rb
class Event < ActiveRecord::Base
    attr_accessible :title, :minbits,:status
    has_many :bits
    validates :title, :status, presence: true
    validates :minbits, numericality: {greater_than_or_equal_to: 100}
    validates :title, uniqueness: true
    
  def self.make_status
    Event.all.map! do |event|
      event.status = [:loss, :win].sample
      event.save
    end
  end  

 def self.make_suspense
    Event.all.map! do |event|
      event.status = :suspense
      event.save
    end
  end  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  inherit_resources
  
  def index
    @events = Event.order(:title)
  end

  def make_bit
    user = current_user
    event = Event.find(params[:id])
    if event.status == "suspense"
      bit = Bit.create(user_id: user.id, event_id: event.id, sum: event.minbits, payed: false)
      notice = 'Bit was successfully created.'
      redirect_to events_url, notice: notice
    else
      redirect_to events_url, notice: 'Bit is already not use'
    end  
     
  end
  
  def make_status_bits
    begin
      Event.make_status
      User.add_balance
      redirect_to events_url, notice: 'All bits make' 
    rescue
      redirect_to events_url, notice: 'No wallet'
    end
  end
  
  def cancel_status_bits
    Event.make_suspense
    redirect_to events_url, notice: 'All make' 
  end
  private
 
  def find_current_bit
    bit = Bit.find_by_id(session[:bit_id])
    if bit.nil?
      bit = Bit.create(user_id: current_user.id, payed: false)
      session[:bit_id] = bit.id
    end
    bit
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :minbits
    %br/
    = f.text_field :minbits
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .actions
    = f.submit

app/views/events/edit.html.haml
- if can? :create, Event
  %h1 Editing event
  = render 'form'
  = link_to 'Show', @event
  |
  \#{link_to 'Back', events_path}

app/views/events/index.html.haml
- if notice
  %p#notice= notice
%h1 Listing events
%table
  - @events.each_with_index do |event, index|
    %tr{:class => "<haml:silent>cycle('list_line_odd', 'list_line_even') </haml:silent>"}
    %tr
      %td.list_description
        %dl
          %dt= event.title
          %dt= event.status
          %dt
            $#{event.minbits}
          - if !current_user.bits.find_by_event_id(event.id)
            %dt= button_to "Make bit #{index}", {action: :make_bit, id: event.id}, :class => "btn btn-primary", id: "button_#{index}"
      %td.list_actions
        = link_to 'Show', event
        %br/
        - if can? :create, Event
          = link_to 'Edit', edit_event_path(event)
          %br/
        - if can? :destroy, Event
          = link_to 'Destroy', event,  |
            confirm: 'Are you sure?' , |
            method: :delete            |
- if can? :create, Event
  %dt= button_to 'Make_status_bits', {action: :make_status_bits}, :class =>"btn btn-primary "
  %dt= button_to 'Cancel_status_bits', {action: :cancel_status_bits}, :class =>"btn btn-primary "
  %br/
  = link_to 'New Event', new_event_path

       

app/views/events/new.html.haml
- if can? :create, Event
  %h1 New event
  = render 'form'
  = link_to 'Back', events_path

app/views/events/show.html.haml
<p #{'Bits show'}
%h1
  = @event.title
  %h3
    %td= @event.status
    %td= @event.minbits
    - if can? :manage, Bit
      = button_to 'Edit', edit_event_path(@event)
      
    = link_to 'Back', events_path

  