config/routes.rb
Totalizator::Application.routes.draw do
  
  resources :user_bits


  #resources :line_items


  resources :bits


  resources :wallets


  #get "events/index"

  resources :events
  #get ':controller/:action/:event_id'

  #resources :posts
  resources :events do
    post :make_bit, :on => :member
  end
  
  resources :events do
      post :it_exist, :on => :member
  end

  resources :bits do
    collection do 
      post :pay_bits
    end
  end
  


resources :bits do
    collection do 
      post :pay_this_bit
    end
end



  resources :bits do
    collection do 
      post :see_balance
    end
  end

  resources :events do
    collection do 
      post :make_status_bits
    end
  end
  
  resources :events do
    collection do 
      post :cancel_status_bits
    end
  end
  devise_for :users

  root to: "home#index"


end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  attr_accessible :balance, :user_id
  belongs_to :user
  
  #before_validation :set_balance, on: :create
  #validates :balance, numericality: {greater_than_or_equal_to: 100}
  
  private

    def set_balance
      balance ||= 10000
    end

    
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
   inherit_resources 
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.haml
= form_for(@wallet) do |f|
  - if @wallet.errors.any?
    #error_explanation
      %h2
        = pluralize(@wallet.errors.count, "error")
        prohibited this wallet from being saved:
      %ul
        - @wallet.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :balance
    %br/
    = f.text_field :balance
  .actions
    = f.submit

app/views/wallets/edit.html.haml
%h1 Editing wallet
- if notice
  %p#notice= notice
= render 'form'
= link_to 'Show', wallets_url
|
\#{link_to 'Back', wallet_path}

app/views/wallets/index.html.haml
%h1 Listing wallets
%h2
  \-----------------------
  %h2
    %table
      %tr
        %th
        %th
        %th
      
        - if can? :create, Event
          - @wallets.each do |wallet|
            %ol
              
              %h3
                Wallets id: #{wallet.id}
              %h3
              %h3
                Balance: #{wallet.balance}
              %h3
              %h3
                email: #{wallet.user.email}
              %h3
              %ul
                %h4 User bits
                %h4
                - wallet.user.bits.each do |bit|
                  %li
                    %h5
                      = bit.event.title
                      = bit.sum
                    %h5/
                %ul/    
              = link_to 'Show', wallet
              %br/
              = link_to 'Edit', edit_wallet_path(wallet)
              %br/
              = link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' }
              %br/
            
            
    %br/

app/views/wallets/new.html.haml
%h1 New wallet
= render 'form'
= link_to 'Back', wallet_path

app/views/wallets/show.html.haml
- if notice
  %p#notice= notice
%tr
  %h1
    Your balance
    %h1
      - if @wallet.user_id == current_user.id
        %h2= @wallet.balance
        %h2
          = button_to 'Edit', edit_wallet_path(@wallet), :method => :get, :class => "btn btn-danger", id: "edit_balance"
        %h2
          = link_to 'Back', events_url, :class =>"btn btn-primary "
          