config/routes.rb
Totalizator::Application.routes.draw do
  
  resources :user_bits


  #resources :line_items


  resources :bits


  resources :wallets


  #get "events/index"

  resources :events
  #get ':controller/:action/:event_id'

  #resources :posts
  resources :events do
    post :make_bit, :on => :member
  end
  
  resources :events do
      post :it_exist, :on => :member
  end

  resources :bits do
    collection do 
      post :pay_bits
    end
  end
  


resources :bits do
    collection do 
      post :pay_this_bit
    end
end



  resources :bits do
    collection do 
      post :see_balance
    end
  end

  resources :events do
    collection do 
      post :make_status_bits
    end
  end
  
  resources :events do
    collection do 
      post :cancel_status_bits
    end
  end
  devise_for :users

  root to: "home#index"


end

app/models/bit.rb
class Bit < ActiveRecord::Base
 attr_accessible :user_id, :sum, :event_id, :payed
  #has_many :lines_items, dependent: :destroy
  belongs_to :user
  belongs_to :event
  validates :sum, numericality: {greater_than_or_equal_to: 99}  
   
  
      
end

app/controllers/bits_controller.rb
class BitsController < ApplicationController
  inherit_resources
  def index
    begin
      @bits = Bit.all
      @user = current_user
    rescue
      redirect_to events_url, notice: 'Please login or register'
    end
  end

  def show
    begin
      @bit = Bit.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "bits number #{params[:id]} not found"
      redirect_to events_index_url, notice: 'not found bits'
    end
  end

  def update
    @bit = Bit.find(params[:id])
    if @bit.update_attributes(params[:bit])
        if @bit.sum < @bit.event.minbits
           @bit.sum = @bit.event.minbits
           @bit.save
           redirect_to @bit, notice: 'Your summa is small. Edit abort' 
        else
        redirect_to @bit, notice:  'Bit was successfully updated.'
        end
    else
    render action: "edit" 
    end
  end


def pay_this_bit
  @bit = Bit.find(params[:id])
  @wallet = find_current_wallet
    if @wallet.balance>=@bit.sum
      @wallet.balance-=@bit.sum
      @wallet.save
      @bit.payed = true
      @bit.save
      redirect_to bits_url, notice: "Bit are made. Your balance is:#{@wallet.balance}."
    else
          redirect_to wallet_path(@wallet), notice: "Bits are not made. Your balance is:#{@wallet.balance}." 
    end      
end

def pay_bits
  
  user = current_user  
  sum_of_pay=user.sum_pay
  if sum_of_pay==0
    redirect_to events_url, notice: "You have already paid bits in your list. You can pay for the new."
    #throw sum_of_pay
    else
    @wallet = find_current_wallet
    if @wallet.balance>=sum_of_pay
      @wallet.balance-=sum_of_pay
      @wallet.save
      user.price
      sum_of_pay=0
      redirect_to bits_url, notice: "Bits are made. Your balance is:#{@wallet.balance}."
    else
      redirect_to wallet_path(@wallet), notice: "Bits are not made. Your balance is:#{@wallet.balance}." 
    end
  end
end

def see_balance
  begin
    @wallet = find_current_wallet
    redirect_to wallet_path(@wallet), notice: "#{current_user.wallet.id}redirect to your balance:"  
  rescue
  redirect_to wallet_path(@wallet), notice: "Your wallet is create"  
  end
end

def find_current_wallet
  current_user.wallet ? current_user.wallet : Wallet.create(user_id: current_user.id)
end


end

app/helpers/bits_helper.rb
module BitsHelper
end

app/views/bits/_form.html.haml
= form_for(@bit) do |f|
  - if @bit.errors.any?
    #error_explanation
      %h2
        = pluralize(@bit.errors.count, "error")
        prohibited this bit from being saved:
      %ul
        - @bit.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :sum
    %br/
    = f.number_field :sum
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :event_id
    %br/
    = f.number_field :event_id
  .actions
    = f.submit

app/views/bits/edit.html.haml
%h1 Editing bit
= render 'form'
= link_to 'Show', @bit
|
\#{link_to 'Back', bits_path}

app/views/bits/index.html.haml
- if notice
  %p#notice= notice
%h1 Listing bits
%table
  %tr
    %th
    %th
    %th
  %ul
    - @user.bits.each do |bit|
      %li
        = bit.event.title
        \&times; #{bit.sum}
        - if !bit.payed?
          = link_to 'Edit', edit_bit_path(id: bit.id)
          %br/
        - if !bit.payed? 
          = button_to 'Pay pay_this_bit', {action: :pay_this_bit, id: bit.id}, :class =>"btn btn-primary "
          %br/
        = link_to 'Destroy', bit,    |
          confirm: 'Are you sure?' , |
          method: :delete            |
  %tr.total_line
    %td{:colspan => "2"} Total
    %td.total_cell= number_to_currency(@user.sum_pay)
  
  %td= button_to 'Pay bits', {action: :pay_bits}, :class => "btn btn-danger", id: "pay_bits"
  %td= button_to 'See_balance',{action: :see_balance},:class => "btn btn-danger", id: "See_balance"

app/views/bits/new.html.haml
%h1 New bit
= render 'form'
= link_to 'Back', bits_path

app/views/bits/show.html.haml
- if notice
  %p#notice= notice
%h2 Your Bits
%ul
  %li
    = @bit.event.title
    \&times; #{@bit.sum}
    \#{link_to 'Edit', edit_bit_path(id: @bit.id)}